config/routes.rb
Mindroad::Application.routes.draw do
  resources :sectors

  resources :roads do
    get :map, on: :member, :as => :map
  end 

  resources :columns do
    put 'delete_unit', :on => :member, :as => :delete_unit
  end

  resources :links

  resources :units

  root :to => 'units#index'

 

end

app/models/sector.rb
class Sector < ActiveRecord::Base
  attr_accessible :title

  has_many :roads

end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  # GET /sectors
  # GET /sectors.json
  def index
    @sectors = Sector.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sectors }
    end
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
    @sector = Sector.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sector }
    end
  end

  # GET /sectors/new
  # GET /sectors/new.json
  def new
    @sector = Sector.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sector }
    end
  end

  # GET /sectors/1/edit
  def edit
    @sector = Sector.find(params[:id])
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(params[:sector])

    respond_to do |format|
      if @sector.save
        format.html { redirect_to @sector, notice: 'Sector was successfully created.' }
        format.json { render json: @sector, status: :created, location: @sector }
      else
        format.html { render action: "new" }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sectors/1
  # PUT /sectors/1.json
  def update
    @sector = Sector.find(params[:id])

    respond_to do |format|
      if @sector.update_attributes(params[:sector])
        format.html { redirect_to @sector, notice: 'Sector was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector = Sector.find(params[:id])
    @sector.destroy

    respond_to do |format|
      format.html { redirect_to sectors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.erb
<%= form_for(@sector) do |f| %>
  <% if @sector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sector.errors.count, "error") %> prohibited this sector from being saved:</h2>

      <ul>
      <% @sector.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sectors/edit.html.erb
<h1>Editing sector</h1>

<%= render 'form' %>

<%= link_to 'Show', @sector %> |
<%= link_to 'Back', sectors_path %>

app/views/sectors/index.html.erb
<h1>Listing sectors</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sectors.each do |sector| %>
  <tr>
    <td><%= sector.title %></td>
    <td><%= link_to 'Show', sector %></td>
    <td><%= link_to 'Edit', edit_sector_path(sector) %></td>
    <td><%= link_to 'Destroy', sector, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sector', new_sector_path %>

app/views/sectors/new.html.erb
<h1>New sector</h1>

<%= render 'form' %>

<%= link_to 'Back', sectors_path %>

app/views/sectors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @sector.title %>
</p>


<%= link_to 'Edit', edit_sector_path(@sector) %> |
<%= link_to 'Back', sectors_path %>