config/routes.rb
Mindroad::Application.routes.draw do
  resources :sectors

  resources :roads do
    get :map, on: :member, :as => :map
  end 

  resources :columns do
    put 'delete_unit', :on => :member, :as => :delete_unit
  end

  resources :links

  resources :units

  root :to => 'units#index'

 

end

app/models/column.rb
class Column < ActiveRecord::Base
  attr_accessible :first_line, :fourth_line, :road_id, :second_line, :third_line
  
  has_many :units
  belongs_to :road
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  # GET /columns
  # GET /columns.json
  
  helper :all

  def index
    @columns = Column.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @columns }
    end
  end

  # GET /columns/1
  # GET /columns/1.json
  def show
    @column = Column.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @column }
    end
  end

  # GET /columns/new
  # GET /columns/new.json
  def new
    @column = Column.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @column }
    end
  end

  # GET /columns/1/edit
  def edit
    @column = Column.find(params[:id])
  end

  # POST /columns
  # POST /columns.json
  def create
    @column = Column.new(params[:column])

    respond_to do |format|
      if @column.save
        format.html { redirect_to @column, notice: 'column was successfully created.' }
        format.json { render json: @column, status: :created, location: @column }
      else
        format.html { render action: "new" }
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /columns/1
  # PUT /columns/1.json
  def update
    @column = Column.find(params[:id])

    respond_to do |format|
      if @column.update_attributes(params[:column])
        format.html { redirect_to @column, notice: 'column was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @column.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /columns/1
  # DELETE /columns/1.json
  def destroy
    @column = Column.find(params[:id])
    @column.destroy

    respond_to do |format|
      format.html { redirect_to columns_url }
      format.json { head :no_content }
    end
  end

  def delete_unit

    @column = Column.find(params[:id])
    
    if @column.first_line.to_s == params[:unit_id]
      @column.update_attributes(:first_line => '0')
    end
    if @column.second_line.to_s == params[:unit_id]
      @column.update_attributes(:second_line => '0')
    end
    if @column.third_line.to_s == params[:unit_id]
      @column.update_attributes(:third_line => '0')
     end
    if @column.fourth_line.to_s == params[:unit_id]
      @column.update_attributes(:fourth_line => '0')
    end

    @column.save

    if @column.errors.empty?
      flash[:notice] = 'unit with id=' + params[:unit_id].to_s + ' has been removed from this map'
      redirect_to map_road_path(:id => @column.road_id)
    else
      render "edit"
    end

  end

end

app/helpers/columns_helper.rb
module ColumnsHelper

end

app/views/columns/_form.html.erb
<%= form_for(@column) do |f| %>
  <% if @column.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@column.errors.count, "error") %> prohibited this column from being saved:</h2>

      <ul>
      <% @column.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :road_id %><br />
    <%= f.number_field :road_id %>
  </div>
  <div class="field">
    <%= f.label :index_number_in_road %><br />
    <%= f.number_field :index_number_in_road %>
  </div>
  <div class="field">
    <%= f.label :first_line %><br />
    <%= f.number_field :first_line %>
  </div>
  <div class="field">
    <%= f.label :second_line %><br />
    <%= f.number_field :second_line %>
  </div>
  <div class="field">
    <%= f.label :third_line %><br />
    <%= f.number_field :third_line %>
  </div>
  <div class="field">
    <%= f.label :fourth_line %><br />
    <%= f.number_field :fourth_line %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/columns/edit.html.erb
<h1>Editing column</h1>

<%= render 'form' %>

<%= link_to 'Show', @column %> |
<%= link_to 'Back', columns_path %>

app/views/columns/index.html.erb
<h1>Listing columns</h1>

<table>
  <tr>
    <th>Road_id</th>
    <th>Index number</th>
    <th>First line</th>
    <th>Second line</th>
    <th>Third line</th>
    <th>Fourth line</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @columns.each do |column| %>
  <tr>
    <td><%= column.id %></td>
    <td><%= column.index_number_in_road %></td>
    <td><%= column.road_id %></td>
    <td><%= column.first_line %></td>
    <td><%= column.second_line %></td>
    <td><%= column.third_line %></td>
    <td><%= column.fourth_line %></td>
    <td><%= link_to 'Show', column %></td>
    <td><%= link_to 'Edit', edit_column_path(column) %></td>
    <td><%= link_to 'Destroy', column, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New column', new_column_path %>

app/views/columns/new.html.erb
<h1>New column</h1>

<%= render 'form' %>

<%= link_to 'Back', columns_path %>

app/views/columns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Road_id:</b>
  <%= @column.road_id %>
</p>

<p>
  <b>Index number:</b>
  <%= @column.index_number_in_road %>
</p>

<p>
  <b>First line:</b>
  <%= @column.first_line %>
</p>

<p>
  <b>Second line:</b>
  <%= @column.second_line %>
</p>

<p>
  <b>Third line:</b>
  <%= @column.third_line %>
</p>

<p>
  <b>Fourth line:</b>
  <%= @column.fourth_line %>
</p>


<%= link_to 'Edit', edit_column_path(@column) %> |
<%= link_to 'Back', columns_path %>