config/routes.rb
Mindroad::Application.routes.draw do
  resources :sectors

  resources :roads do
    get :map, on: :member, :as => :map
  end 

  resources :columns do
    put 'delete_unit', :on => :member, :as => :delete_unit
  end

  resources :links

  resources :units

  root :to => 'units#index'

 

end

app/models/road.rb
class Road < ActiveRecord::Base
  attr_accessible :sector_id, :title
  
  has_many :columns
  has_many :units
  belongs_to :sector
end

app/controllers/roads_controller.rb
class RoadsController < ApplicationController
  # GET /roads
  # GET /roads.json
  def index
    @roads = Road.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roads }
    end
  end

  # GET /roads/1
  # GET /roads/1.json
  def show
    @road = Road.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @road }
    end
  end

  # GET /roads/new
  # GET /roads/new.json
  def new
    @road = Road.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @road }
    end
  end

  # GET /roads/1/edit
  def edit
    @road = Road.find(params[:id])
  end

  # POST /roads
  # POST /roads.json
  def create
    @road = Road.new(params[:road])

    respond_to do |format|
      if @road.save
        format.html { redirect_to @road, notice: 'Road was successfully created.' }
        format.json { render json: @road, status: :created, location: @road }
      else
        format.html { render action: "new" }
        format.json { render json: @road.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roads/1
  # PUT /roads/1.json
  def update
    @road = Road.find(params[:id])

    respond_to do |format|
      if @road.update_attributes(params[:road])
        format.html { redirect_to @road, notice: 'Road was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @road.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roads/1
  # DELETE /roads/1.json
  def destroy
    @road = Road.find(params[:id])
    @road.destroy

    respond_to do |format|
      format.html { redirect_to roads_url }
      format.json { head :no_content }
    end
  end

  def map
    @road_columns = Column.where(:road_id => params[:id]).order("index_number_in_road")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def delete_unit
    @column_pre = Column.find(params[:id])

    if @column_pre.first_line == params[:unit_id]
      @column_pre.update_column(:first_line, '0')
    end
    if @column_pre.second_line == params[:unit_id]
      @column_pre.update_attribute('second_line', '0')
    end
    if @column_pre.third_line == params[:unit_id]
      @column_pre.update_attribute('third_line', '0')
     end
    if @column_pre.fourth_line == params[:unit_id]
      @column_pre.update_attribute('fourth_line', '0')
    end
    
    save
    
    if @column_pre.errors.empty?
      redirect_to map_url(:id => unit_id)
    else
      render "edit"
    end
    
  end

end

app/helpers/roads_helper.rb
module RoadsHelper

  def check_unit(unit_id, line, road_id, id)
    if Unit.exists?(:id => unit_id)
      
      @text_str = link_to Unit.find(unit_id).title, unit_path(unit_id)

      @link_delete = link_to "&times;".html_safe, delete_unit_column_path(:id => id, :unit_id => unit_id), 
                      :data => {:confirm => 'Are you sure?'},
                      :id => id,
                      :method => :put,
      								:action => :delete_unit,
                    	:class => 'close',
                      :unit_id => unit_id


      @str = "<div class='unit'>" + unit_id.to_s + ". " + @text_str.to_s + "<br>" + @link_delete + "</div>".html_safe

      return @str
    else
      @str = "<div class='unit'>clear</div>".html_safe
      return @str
    end
  end
  
end

app/views/roads/_form.html.erb
<%= form_for(@road) do |f| %>
  <% if @road.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@road.errors.count, "error") %> prohibited this road from being saved:</h2>

      <ul>
      <% @road_map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :sector_id %><br />
    <%= f.number_field :sector_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roads/edit.html.erb
<h1>Editing road</h1>

<%= render 'form' %>

<%= link_to 'Show', @road %> |
<%= link_to 'Back', roads_path %>

app/views/roads/index.html.erb
<%- model_class = Road -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:sector_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @roads.each do |road| %>
      <tr>
        <td><%= link_to road.id, link_path(road) %></td>
        <td><%= road.title %></td>
        <td><%= road.sector_id %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.roads.edit")),
                      edit_road_path(road), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.roads.destroy")),
                      road_path(road),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.roads.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New road', new_road_path %>

app/views/roads/map.html.erb
<%- model_class = Road -%>

<div class='page-header'>
  <h3>Road: Введение в Ruby on Rails<h3>
</div>

<div class="scroll">

  <div class="scroll_child">

   		    <% @road_columns.each do |column| %>

		      <div class='column'>
            
		        <%= raw check_unit(column.first_line, "first_line", column.road_id, column.id) %>
		        <%= raw check_unit(column.second_line, "second_line", column.road_id, column.id) %>
		        <%= raw check_unit(column.third_line, "third_line", column.road_id, column.id) %>
		        <%= raw check_unit(column.fourth_line, "fourth_line", column.road_id, column.id) %>
            
		      </div>
       

		      <% end %>



	</div>
</div>


app/views/roads/new.html.erb
<h1>New road</h1>

<%= render 'form' %>

<%= link_to 'Back', roads_path %>

app/views/roads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @road.title %>
</p>

<p>
  <b>Sector:</b>
  <%= @road.sector_id %>
</p>


<%= link_to 'Edit', edit_road_path(@road) %> |
<%= link_to 'Back', roads_path %>