config/routes.rb
Mindroad::Application.routes.draw do
  resources :sectors

  resources :roads do
    get :map, on: :member, :as => :map
  end 

  resources :columns do
    put 'delete_unit', :on => :member, :as => :delete_unit
  end

  resources :links

  resources :units

  root :to => 'units#index'

 

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :description, :road_id, :title
  
  has_many :links
  belongs_to :road
  belongs_to :column
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  # GET /units
  # GET /units.json
  def index
    @units = Unit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @units }
    end
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @unit = Unit.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit }

    end

  end

  # GET /units/new
  # GET /units/new.json
  def new
    @unit = Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render json: @unit, status: :created, location: @unit }
      else
        format.html { render action: "new" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.json
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/units_helper.rb
module UnitsHelper

end

app/views/units/_form.html.erb
<%= form_for @unit, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area', rows: '6' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :road_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :road_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                units_path, :class => 'btn' %>
  </div>
<% end %>

app/views/units/_links_tab.html.erb
<%- model_class = Unit -%>

<% @links = Link.where(:unit_id => params[:id], :url_type => type) %>

<% if @links.count != 0 %>
    
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Заголовок</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @links.each do |link| %>
	        <tr>
	          <td><%= link_to link.id, link_path(link) %></td>
	          <td><%= link_to link.title, link.url %></td>
	          <td><div class='btn-group'>
	          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_link_path(link), :class => 'btn btn-mini' %>

	          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      link_path(link),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
	          </div></td>
	        </tr>
        <% end %>
      </tbody>
    </table>
<% else %>
	<h4> --- There are no any links here now --- </h4>
<% end %>

app/views/units/edit.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/units/index.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:road_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= link_to unit.id, unit_path(unit) %></td>
        <td><%= link_to unit.title, unit_path(unit) %></td>
        <td><%= unit.description %></td>
        <td><%= unit.road_id %></td>
        <td nowrap="nowrap">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_unit_path(unit), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      unit_path(unit),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_unit_path,
            :class => 'btn btn-primary' %>

app/views/units/new.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/units/show.html.erb
<%- model_class = Unit -%>

<div class="page-header">

  <dl class="dl-horizontal">
    <dt><strong>Сектор:</strong></dt>
    <dd><%= @unit.road.sector.title %></dd>
    <dt><strong>Курс:</strong></dt>
    <dd><%= @unit.road.title %></dd>
    <dt><strong>Юнит:</strong></dt>
    <dd><%= @unit.title %></dd>
  </dl>

  <div class="btn-group btn-group-vertical">
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_unit_path(@unit), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                unit_path(@unit),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Вы уверены?')) },
                :class => 'btn btn-danger' %>
  </div>

</div>

<div class='main-page'>
  <ul class="nav nav-tabs">
    <li><a                href="#recommended" data-toggle="tab">    Рекомендуемые   </a></li>
    <li class="active"><a href="#articles" data-toggle="tab">       Статьи          </a></li>
    <li><a                href="#videos" data-toggle="tab">         Видео           </a></li>
    <li><a                href="#books" data-toggle="tab">          Книги           </a></li>
    <li><a                href="#courses" data-toggle="tab">        Курсы           </a></li>
    <li><a                href="#shop" data-toggle="tab">           Магазин         </a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane"         id="recommended"  >...</div>
    <div class="tab-pane active"  id="articles"     ><%= render partial: 'links_tab', locals: { type: 1} %></div>
    <div class="tab-pane"         id="videos"       ><%= render partial: 'links_tab', locals: { type: 2} %></div>
    <div class="tab-pane"         id="books"        ><%= render partial: 'links_tab', locals: { type: 3} %></div>
    <div class="tab-pane"         id="courses"      ><%= render partial: 'links_tab', locals: { type: 4} %></div>
    <div class="tab-pane"         id="shop"         ><%= render partial: 'links_tab', locals: { type: 5} %></div>

      <%= link_to t('.new', :default => t("helpers.links.new")),
            new_link_path,
            :class => 'btn btn-primary' %>
  </div>



  <div class='comment-tab'>

    <div class ='comment'>
      <div>
        <div><small>Комментарий оставлен: 04/12/13</small>
          <span itemprop="datePublished" content="2013-04-12"></span>
        </div>
        <div>
          <i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i>
          <small><strong>7</strong> из <strong>11</strong> людей сочли этот комментарий полезным.</small>
        </div>
      </div>
      <div class="trrln spcln">
        <div>
          <h5>"Классная ссылка, вся инфа в одном месте"</h5><small>by: politenessman129</small><br>
        </div>
      </div>
      <div><p>i dont have an iphone, verizon charges $30 per month minimum for data, plus charges for texting, and usage. this is my first apple product, i wanted something to occupy my time commuting, lunch, downtime, also play music. really nice, packaged well, setup is easy, works great. i got the mini because i can hold it in 1 hand, couldnt (dont think anybody can) hold the ipad standard in 1 hand. text is sometimes a little small, and i am pressing things i dont mean to. but i will prob get more accurate as i go on. bought a nice case for it (dodo classic) and plan on trying to keep it in great condition</p>
      </div>
    </div>
  </div>

</div>

  <div class="sub-footer">
    <ul class="pager">
    <li class="previous">
      <a href="#">&larr; Предыдущий юнит</a>
    </li>
    <li class="next">
      <a href="#">Следующий юнит &rarr;</a>
    </li>
  </ul>
  </div>

<script type="text/javascript">
  $(document).ready(function(){

    $('#articles a').click(function (e) {
      e.preventDefault();
      $(this).tab('show');
    })

  }
</script>